version: '3.8'
name: project-manager

volumes:
  db:
    driver: local

services:
  api:
    container_name: proj-manager-api
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/project_manager?schema=public
      - JWT_SECRET=prod-secret
      - PORT=4000
    depends_on:
      - db
  db:
    container_name: proj-manager-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=project_manager
    volumes:
      - /db
